### ISSUE TITLE
ovfconf syntax error: unexpected end of file

### ISSUE THREAD

**Issue by KipFisher** [veksh/ovfconf#1]
I've got everything in place, deploy a OVF, but ovfconf errors out with "/usr/local/sbin/ovfconf: line 391: syntax error: unexpected end of file"

**Comment by veksh** [comment]
Sorry for long delay, missed bug notification mail :)

Please try latest version, I've fixed most probable cause (typo in check, introduced at last commit).

**Comment by veksh** [comment]
Seems to be ok now.
