### ISSUE TITLE
does not detect IP when interface is dhcp

### ISSUE THREAD

**Issue by giondo** [veksh/ovfconf#2]
when there is not IP configured on the ifcfg-ens* file it give you an error
this way doesn't  matter if the IP is on  the file or just got it by dhcp
proposed change:

export old_ip=$(ip addr show $if0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f2)

**Comment by veksh** [comment]
It is by design: script assumes that template host has static IP, and it must be changed to another static IP.
Why do you need OVF config if your environment relies on DHCP to assign ip/hostname/gw?
